### ISSUE TITLE
404 on DELETE fictive Resource

### ISSUE THREAD

**Issue by bourgeoa** [solid-contrib/specification-tests#112]
https://github.com/solid-contrib/specification-tests/blob/6fe781855cdf0104909123ee0c28624f4bed4fd6/web-access-control/protected-operation/write-access-bob.feature#L146

 https://github.com/solid-contrib/specification-tests/blob/6fe781855cdf0104909123ee0c28624f4bed4fd6/web-access-control/protected-operation/write-access-public.feature#L119

Tests harness expects 403/401 depending;
test on NSS fails with returning status 404 in such situation.
Should this be accepted ?

**Comment by edwardsph** [comment]
See discussions here: https://github.com/solid/specification/issues/14#issuecomment-683480525 and in related issues on why a 404 is not accepted

**Comment by bourgeoa** [comment]
Resolved with https://github.com/nodeSolidServer/node-solid-server/commit/809e0ac7361d642fdeed3731505ba28ad724a5bb
