### ISSUE TITLE
If-none-match on NSS returns 201 for PUT on existing resource

### ISSUE THREAD

**Issue by bourgeoa** [solid-contrib/specification-tests#115]
https://github.com/solid-contrib/specification-tests/blob/6fe781855cdf0104909123ee0c28624f4bed4fd6/protocol/writing-resource/if-none-match-asterisk.feature#L7

Conformance test expects 412

**Comment by edwardsph** [comment]
If the resource already exists, then PUT with If-None-Match=* should fail

**Comment by bourgeoa** [comment]
resolved with https://github.com/nodeSolidServer/node-solid-server/commit/59f94fb9f8afabdb03257886b37be6eb33695bb1
